name: CI
run-name: ${{ github.actor }} is running 🚀
on: [push]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.2.2"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Job running on ${{ runner.os }} server"
      - run: echo "Branch is ${{ github.ref }}"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install all dependencies (incl. development)
        run: poetry install --with dev
      - run: echo "Job status is ${{ job.status }}"